markdown:         rdiscount
pygments:         true
paginate:         4

title:            TA
feed:             /atom.xml
author:
    name:         fengguiyushao
    email:        fengguiyushao@gmail.com
    description:  "fengguiyushao's Home"

about:            "I am fengguiyushao.I love all kinds of design, attention to the Internet dynamic, dedicated web front development, learn UI and DOTA."
follow:
    email:        fengguiyushao@gmail.com
    github:       https://github.com/fengguiyushao
description:      fengguiyushao's Home

indexContent:     true


style:            /css/style.css
blogName:         TA
blogDesc:         Just Home
favicon:          /favicon.ico
theme:            default

disqus:           robinzhoublog

copyright:        Copyright © 2011-2012 fengguiyushao All rights reserved.
test:             ok
